# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Eduard Kazakov
title: Specialist in GIS and Earth remote sensing, Cartographer, Researcher
email: ee.kazakov@gmail.com
website: www.github.com/eduard-kazakov

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  eduard-kazakov
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: eduard.kazakov.gis
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Telegram
  icon: fab fa-telegram
  url: https://www.t.me/kazakov_e
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/ekazakov.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
          ![Trees](/cv/images/landscape-trees.jpg "Trees")

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: NextGIS
        link: nextgis.com
        sub_title: Director of Educational programs
        caption: January 2021 - Present
        quote: >
          NextGIS is well-known company, developing full stack opensouce GIS software: server, desktop and mobile
        description: | # this will include new lines to allow paragraphs
            Managing processes around education, community and public relations. Developing and conducting of educational courses for NextGIS Software, QGIS, GRASS, SAGA etc. Consulting. Presentations for clients.
            
      - layout: left
        title: State Hydrological Institute
        link: hydrology.ru/en
        sub_title: Head of Geoinformatics group
        caption: March 2019 - January 2021
        quote: >
          State Hydrological Institute is a center of water resources research in Russia
        description: | # this will include new lines to allow paragraphs
            Managing small but gorgeus group of researchers and software developers. Scientific research in field of water resources and hydrological processes modeling on basis of GIS and remote sensing data. Developing software, making maps (a lot of!), writing papers.
            
      - layout: left
        title: Nansen International Environmental and Remote Sensing Center
        link: niersc.spb.ru
        sub_title: Researcher
        caption: March 2016 - December 2018
        quote: >
          NIERSC is russian branch of Norway-based Nansen's center, conducting advanced research in the field of remote sensing of environment
        description: | # this will include new lines to allow paragraphs
            Scientific research in two research groups: «Aquatic ecosystems in response to global change» and «Applied meteorological and oceanographic research». Processing satellite remote sensing data, developing automated environmental monitoring system, writing papers.

      - layout: left
        title: Saint Petersburg State University
        link: spbu.ru
        sub_title: Lecturer
        caption: September 2014 - July 2017
        description: | # this will include new lines to allow paragraphs
            Lecturing at department of cartography and geoinformatics. Conductiong courses: basics of GIS, basics of Earth Remote Sensing, basics of Photogrammetry, basics of Geodesy, GIS for human geography.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Saint Petersburg State University
        caption: 2009 - 2014
        sub_title: Specialist in Geoinformatics (equal to MSc)
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          During my time at Saint Petersburg State University I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          ...

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/cv/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
